//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CommerceEntities1 : DbContext
    {
        public CommerceEntities1()
            : base("name=CommerceEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CMRC_Categories> CMRC_Categories { get; set; }
        public virtual DbSet<CMRC_Customers> CMRC_Customers { get; set; }
        public virtual DbSet<CMRC_OrderDetails> CMRC_OrderDetails { get; set; }
        public virtual DbSet<CMRC_Orders> CMRC_Orders { get; set; }
        public virtual DbSet<CMRC_Products> CMRC_Products { get; set; }
        public virtual DbSet<CMRC_ShoppingCart> CMRC_ShoppingCart { get; set; }
        public virtual DbSet<CMRC_Reviews> CMRC_Reviews { get; set; }
    }
}
